'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("memory.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property achterkant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("achterkant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb43() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb43", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb44() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb44", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Afb46() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Afb46", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
